### ISSUE TITLE
Unable to run on macOS

### ISSUE THREAD

**Issue by afkcodes** [vaithak/Sudoku-Generator#3]
hello @vaithak this is really awesome, loved it . although i am unable to run it on macOS 
returns the following error
```
sudokuGen
zsh: command not found: sudokuGen
```

this is what i have in my bash_profile
```
alias 'sudokuGen'='/Users/ashish/Sudoku-Generator/sudokuGen'
```

is it possible to create 12x12 & 16x16 sudokus may be also 4x4 & 6x6  ? to be honest i am trying to build a game based on this generator. 
one more thing how can we define the sudoku difficulty ?

**Comment by vaithak** [comment]
Hi @afkcodes, if you have `zsh` as the default shell then you should add this command in the `.zshrc` file instead of bash_profile. Regarding your other query, there is no support for other sizes as of now but feel free to add a PR in case you want to contribute.

**Comment by afkcodes** [comment]
The thing is I am pretty bad at CPP, I use JS for all of my projects but I will surely try one more query was to generate harder puzzles now it generates randomly I guess.

**Comment by vaithak** [comment]
programming language is not a problem. You can implement the algorithm in JS as well, then we can test the correctness and runtime and later port it to C++. The feature of generating puzzles of harder (or any specific) difficulty is still in the back of my mind, I haven't yet thought about it.
